# Generated by Django 5.2.15 on 2026-06-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=120)),
                ('reason', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blacklist entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('restricted', models.BooleanField(default=False, help_text='Restricted zones require explicit admin approval.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
