# Generated by Django 5.2.15 on 2026-06-12 09:53

import apps.visits.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('single_entry', models.BooleanField(default=True)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zones', models.ManyToManyField(blank=True, to='access.zone')),
            ],
            options={
                'verbose_name_plural': 'Passes',
            },
        ),
        migrations.CreateModel(
            name='CheckInEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('IN', 'Checked in'), ('OUT', 'Checked out'), ('DENIED', 'Denied')], max_length=6)),
                ('gate', models.CharField(default='Main Gate', max_length=60)),
                ('photo', models.ImageField(blank=True, upload_to='checkin_photos/')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pass_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='visits.pass')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.visits.models.generate_reference, max_length=12, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('id_type', models.CharField(default='NRC', max_length=30)),
                ('id_number', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_entity', models.BooleanField(default=False, verbose_name='Entity / group visit')),
                ('entity_name', models.CharField(blank=True, max_length=120)),
                ('vehicle_reg', models.CharField(blank=True, max_length=20)),
                ('purpose', models.TextField()),
                ('expected_start', models.DateTimeField()),
                ('expected_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('CHECKED_IN', 'Checked in'), ('CHECKED_OUT', 'Checked out'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_visits', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, help_text='Linked account; null for walk-ins registered by Security.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party', to='visits.visitrequest')),
            ],
            options={
                'verbose_name_plural': 'Visitor party members',
            },
        ),
        migrations.AddField(
            model_name='pass',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_pass', to='visits.visitrequest'),
        ),
        migrations.AddIndex(
            model_name='visitrequest',
            index=models.Index(fields=['status', 'expected_start'], name='visits_visi_status_285dbb_idx'),
        ),
    ]
